name: Manually triggered debug build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Copy WildBox
        run: mkdir -p app/src/main/jniLibs/arm64-v8a && cp wildbox/wildbox app/src/main/jniLibs/arm64-v8a/wildbox.so
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

