name: Manually triggered debug build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew assembleDebug
        with:
            name: APK
            path: app/build/outputs/apk/debug/app-debug.apk

