name: Manually triggered debug build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build WildBox
        run: $ANDROID_SDK_ROOT/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android27-clang -static -fPIE -fPIC wildbox/wildbox.c -o wildbox/wildbox
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Upload WildBox
        uses: actions/upload-artifact@v1
        with:
          name: wildbox
          path: wildbox/wildbox
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

